import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "prod-001",
    slug: "voyager-pro-laptop",
    name: "Voyager Pro Laptop",
    brand: "Veonar",
    category: "electronics",
    price: 499,
    rating: 4.7,
    reviewCount: 342,
    images: [
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794561-7780e723166d?w=800&q=80",
    ],
    description:
      "The Voyager Pro combines a stunning 15.6-inch 4K display with a 12th-gen Intel processor and 32 GB of RAM. Engineered for creators and professionals who demand uncompromising performance in a sleek, lightweight chassis.",
    specs: {
      Processor: "Intel Core i7-12700H",
      RAM: "32 GB DDR5",
      Storage: "1 TB NVMe SSD",
      Display: '15.6" 4K OLED',
      Weight: "1.4 kg",
      "Battery Life": "Up to 14 hrs",
    },
    inStock: true,
    featured: true,
    trending: true,
  },
  {
    id: "prod-002",
    slug: "arc-charge-pad",
    name: "Arc Charge Pad",
    brand: "Pallax",
    category: "electronics",
    price: 39,
    rating: 4.3,
    reviewCount: 128,
    images: [
      "https://images.unsplash.com/photo-1572569511251-c3ba45c8c7a1?w=800&q=80",
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
    ],
    description:
      "A sleek dual-device wireless charging pad with 15 W fast-charge support. Its compact aluminum design fits seamlessly on any nightstand or desk, and intelligent foreign-object detection keeps your devices safe.",
    specs: {
      "Max Output": "15 W",
      Compatibility: "Qi-enabled devices",
      Material: "Aluminum + silicone",
      Dimensions: "16 × 8 × 0.8 cm",
      Weight: "140 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-003",
    slug: "nova-x-smartphone",
    name: "Nova X Smartphone",
    brand: "Vexon",
    category: "electronics",
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.5,
    reviewCount: 517,
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
      "https://images.unsplash.com/photo-1572569511251-c3ba45c8c7a1?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "The Nova X delivers flagship-level performance with a 6.7-inch AMOLED display and a 50 MP triple-camera system. With 5G connectivity and all-day battery life, it keeps you connected wherever you go.",
    specs: {
      Display: '6.7" AMOLED 120 Hz',
      Processor: "Snapdragon 8 Gen 2",
      RAM: "12 GB",
      Storage: "256 GB",
      Camera: "50 MP + 12 MP + 10 MP",
      Battery: "4800 mAh",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-004",
    slug: "vertex-mirrorless-camera",
    name: "Vertex Mirrorless Camera",
    brand: "ArcLens",
    category: "electronics",
    price: 299,
    rating: 4.6,
    reviewCount: 203,
    images: [
      "https://images.unsplash.com/photo-1527814050087-3793815199b5?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794561-7780e723166d?w=800&q=80",
    ],
    badge: "Limited",
    description:
      "Compact mirrorless body with a 24.2 MP APS-C sensor and in-body stabilization. Capture stunning stills and 4K video with fast hybrid autofocus, all in a weather-sealed magnesium body built for adventure.",
    specs: {
      Sensor: "24.2 MP APS-C",
      "ISO Range": "100–32000",
      Stabilization: "5-axis IBIS",
      Video: "4K 60 fps",
      Weight: "460 g",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-005",
    slug: "lumia-over-ear-headphones",
    name: "Lumia Over-Ear Headphones",
    brand: "Lumio",
    category: "audio",
    price: 79,
    originalPrice: 129,
    discount: 39,
    rating: 4.8,
    reviewCount: 891,
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
      "https://images.unsplash.com/photo-1602141521284-9bd31ad95099?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "Immerse yourself in rich, detailed sound with 40 mm neodymium drivers and adaptive noise cancellation. The memory-foam ear cups and 35-hour battery make these the perfect companion for long listening sessions.",
    specs: {
      Drivers: "40 mm neodymium",
      "Frequency Response": "20 Hz – 20 kHz",
      "Noise Cancellation": "Adaptive ANC",
      Connectivity: "Bluetooth 5.3 + 3.5 mm",
      "Battery Life": "Up to 35 hrs",
      Weight: "250 g",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-006",
    slug: "ko-vo-blitz-speaker",
    name: "Ko-Vo Blitz Speaker",
    brand: "Kovo",
    category: "audio",
    price: 59,
    rating: 4.4,
    reviewCount: 176,
    images: [
      "https://images.unsplash.com/photo-1533636727334-9ae4b5c0a6a0?w=800&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    ],
    description:
      "A portable Bluetooth speaker that punches well above its size with dual passive radiators and 20 W of room-filling output. IPX7 waterproofing and a rugged strap let you take the party anywhere.",
    specs: {
      Output: "20 W",
      Drivers: "Dual 52 mm full-range",
      Waterproof: "IPX7",
      Connectivity: "Bluetooth 5.2",
      "Battery Life": "Up to 18 hrs",
      Weight: "540 g",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-007",
    slug: "silta-buds-pro",
    name: "Silta Buds Pro",
    brand: "Siltra",
    category: "audio",
    price: 99,
    rating: 4.6,
    reviewCount: 364,
    images: [
      "https://images.unsplash.com/photo-1602141521284-9bd31ad95099?w=800&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    ],
    badge: "New",
    description:
      "True wireless earbuds with hybrid active noise cancellation and a transparency mode that lets the world in when you need it. Six microphones ensure crystal-clear calls, while customizable EQ lets you shape your sound.",
    specs: {
      Drivers: "11 mm dynamic",
      "Noise Cancellation": "Hybrid ANC",
      Microphones: "6 MEMS",
      "Water Resistance": "IPX5",
      "Battery Life": "8 hrs + 24 hrs case",
      Weight: "5.2 g per bud",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-008",
    slug: "morn-spin-turntable",
    name: "Morn Spin Turntable",
    brand: "Morn",
    category: "audio",
    price: 249,
    rating: 4.8,
    reviewCount: 92,
    images: [
      "https://images.unsplash.com/photo-1533636727334-9ae4b5c0a6a0?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    badge: "Hot",
    description:
      "A belt-driven turntable with an Ortofon 2M Red cartridge, built-in phono preamp, and a solid walnut plinth. The carbon-fiber tonearm and vibration-dampening feet deliver a warm, accurate analog listening experience.",
    specs: {
      Drive: "Belt-drive",
      Cartridge: "Ortofon 2M Red",
      Speeds: "33⅓ / 45 RPM",
      Platter: "Die-cast aluminum",
      Connectivity: "RCA + Bluetooth 5.0",
      Weight: "5.8 kg",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-009",
    slug: "gravis-fit-watch",
    name: "Gravis Fit Watch",
    brand: "Gravit",
    category: "wearables",
    price: 179,
    rating: 4.5,
    reviewCount: 432,
    images: [
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    ],
    description:
      "Track every workout with built-in GPS, heart-rate monitoring, and SpO2 sensing. The vibrant always-on AMOLED display stays readable in direct sunlight, and the lightweight titanium case wears comfortably all day.",
    specs: {
      Display: '1.4" AMOLED Always-On',
      Sensors: "HR, SpO2, GPS, altimeter",
      "Water Resistance": "5 ATM",
      "Battery Life": "Up to 14 days",
      Compatibility: "iOS & Android",
      Weight: "38 g",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-010",
    slug: "nordhal-classic-watch",
    name: "Nordhal Classic Watch",
    brand: "Nordik",
    category: "wearables",
    price: 199,
    rating: 4.7,
    reviewCount: 265,
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
    ],
    description:
      "A minimalist timepiece with a Swiss quartz movement, domed sapphire crystal, and a hand-stitched Italian leather strap. The 40 mm stainless-steel case is polished to a mirror finish for understated elegance.",
    specs: {
      Movement: "Swiss quartz",
      Case: "40 mm stainless steel",
      Crystal: "Domed sapphire",
      Strap: "Italian leather, 20 mm",
      "Water Resistance": "3 ATM",
      Weight: "62 g",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-011",
    slug: "arclens-smart-glasses",
    name: "ArcLens Smart Glasses",
    brand: "ArcLens",
    category: "wearables",
    price: 279,
    rating: 4.3,
    reviewCount: 118,
    images: [
      "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=800&q=80",
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
    ],
    badge: "New",
    description:
      "Fashion-forward frames with built-in open-ear audio and a discreet touch panel for calls and music. Polarized lenses and Bluetooth 5.3 keep you connected without pulling out your phone, and they weigh just 36 grams.",
    specs: {
      Audio: "Open-ear stereo",
      Connectivity: "Bluetooth 5.3",
      Lenses: "Polarized UV400",
      "Battery Life": "Up to 6 hrs playtime",
      "Water Resistance": "IPX4",
      Weight: "36 g",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-012",
    slug: "veonar-sport-band",
    name: "Veonar Sport Band",
    brand: "Veonar",
    category: "wearables",
    price: 29,
    originalPrice: 49,
    discount: 41,
    rating: 4.1,
    reviewCount: 76,
    images: [
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
      "https://images.unsplash.com/photo-1490312278390-ab640c6a7fa9?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "A lightweight fitness band with a sharp OLED display and 14 activity-tracking modes. It monitors steps, calories, sleep, and heart rate continuously, and the soft silicone strap stays comfortable through every workout.",
    specs: {
      Display: '0.96" OLED',
      Sensors: "HR, accelerometer",
      "Water Resistance": "IP68",
      "Battery Life": "Up to 10 days",
      Compatibility: "iOS & Android",
      Weight: "18 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-013",
    slug: "nordhal-messenger-bag",
    name: "Nordhal Messenger Bag",
    brand: "Nordik",
    category: "bags",
    price: 149,
    rating: 4.6,
    reviewCount: 198,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
    ],
    description:
      "Full-grain leather messenger bag with a padded 15-inch laptop sleeve and magnetic flap closure. Multiple interior organizers keep cables, pens, and notebooks tidy, while the adjustable shoulder strap offers all-day carrying comfort.",
    specs: {
      Material: "Full-grain leather",
      Capacity: "18 L",
      "Laptop Sleeve": 'Up to 15.6"',
      Closure: "Magnetic snap + buckle",
      Weight: "920 g",
      "Strap Length": "80–140 cm",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-014",
    slug: "kovo-urban-daypack",
    name: "Kovo Urban Daypack",
    brand: "Kovo",
    category: "bags",
    price: 89,
    rating: 4.5,
    reviewCount: 307,
    images: [
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    description:
      "A weather-resistant daypack with a clean roll-top silhouette and 22 liters of storage. The padded back panel and breathable mesh shoulder straps make it ideal for daily commutes and weekend escapes alike.",
    specs: {
      Material: "Recycled 600D polyester",
      Capacity: "22 L",
      "Laptop Sleeve": 'Up to 15"',
      Closure: "Roll-top with buckle",
      Waterproof: "Water-repellent coating",
      Weight: "680 g",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-015",
    slug: "pallax-tech-pouch",
    name: "Pallax Tech Pouch",
    brand: "Pallax",
    category: "bags",
    price: 34,
    rating: 4.4,
    reviewCount: 54,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1572569511251-c3ba45c8c7a1?w=800&q=80",
    ],
    badge: "New",
    description:
      "Organize your cables, power banks, and chargers in this compact ripstop pouch with elastic loops and mesh pockets. The dual-zipper opening lays flat for quick access, and the water-resistant shell protects your gear.",
    specs: {
      Material: "Ripstop nylon",
      Dimensions: "22 × 12 × 6 cm",
      Pockets: "8 elastic + 2 mesh",
      Waterproof: "Water-resistant shell",
      Weight: "180 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-016",
    slug: "siltra-canvas-tote",
    name: "Siltra Canvas Tote",
    brand: "Siltra",
    category: "bags",
    price: 45,
    rating: 4.3,
    reviewCount: 89,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
    ],
    description:
      "A heavyweight canvas tote with reinforced handles and a reinforced base, perfect for grocery runs, beach days, or carrying your everyday essentials. The interior water-bottle pocket keeps your drink upright.",
    specs: {
      Material: "18 oz cotton canvas",
      Capacity: "25 L",
      Handles: "Reinforced cotton webbing",
      "Interior Pocket": "1 zippered + water-bottle",
      Dimensions: "38 × 32 × 16 cm",
      Weight: "420 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-017",
    slug: "vexon-mek-keyboard",
    name: "Vexon Mek Keyboard",
    brand: "Vexon",
    category: "desk-setup",
    price: 129,
    rating: 4.7,
    reviewCount: 483,
    images: [
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    badge: "Hot",
    description:
      "A tenkeyless mechanical keyboard with hot-swappable Gateron Yellow switches and per-key RGB backlighting. The gasket-mounted PCB and doubleshot PBT keycaps deliver a buttery typing feel built for hours of use.",
    specs: {
      Layout: "TKL (87 keys)",
      Switches: "Gateron Yellow (hot-swap)",
      Keycaps: "Doubleshot PBT",
      Backlight: "Per-key RGB",
      Connectivity: "USB-C detachable",
      Weight: "1.1 kg",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-018",
    slug: "lumio-flex-monitor",
    name: "Lumio Flex Monitor",
    brand: "Lumio",
    category: "desk-setup",
    price: 399,
    rating: 4.6,
    reviewCount: 221,
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    description:
      "A 27-inch 4K USB-C monitor with 95% DCI-P3 coverage and hardware calibration. The ergonomic stand offers tilt, swivel, pivot, and height adjustment, making it the ideal centerpiece for any creative workstation.",
    specs: {
      Display: '27" IPS 4K',
      Resolution: "3840 × 2160",
      "Color Gamut": "95% DCI-P3",
      Refresh: "60 Hz",
      Ports: "USB-C (65 W PD), HDMI, DP",
      Weight: "5.4 kg",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-019",
    slug: "gravis-desk-mat",
    name: "Gravis Desk Mat",
    brand: "Gravit",
    category: "desk-setup",
    price: 24,
    originalPrice: 39,
    discount: 38,
    rating: 4.4,
    reviewCount: 156,
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "A generously sized felt desk mat that covers your entire workspace with a smooth, anti-slip surface. The stitched edges prevent fraying, and the natural wool blend dampens keyboard noise and protects your desk.",
    specs: {
      Material: "Merino wool felt blend",
      Dimensions: "90 × 43 × 0.3 cm",
      "Edge Finish": "Stitched microfiber",
      "Anti-Slip": "Natural rubber backing",
      "Care": "Spot-clean, air dry",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-020",
    slug: "pallax-monitor-arm",
    name: "Pallax Monitor Arm",
    brand: "Pallax",
    category: "desk-setup",
    price: 74,
    rating: 4.5,
    reviewCount: 132,
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80",
    ],
    description:
      "A gas-spring monitor arm that supports screens up to 32 inches and 9 kg with smooth one-touch height adjustment. Integrated cable management and a C-clamp or grommet mount keep your desk clean and spacious.",
    specs: {
      "Screen Size": 'Up to 32"',
      "Weight Capacity": "9 kg",
      Adjustment: "Gas-spring height + tilt",
      "VESA Support": "75 × 75, 100 × 100",
      Mount: "C-clamp or grommet",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-021",
    slug: "lumio-halo-lamp",
    name: "Lumio Halo Lamp",
    brand: "Lumio",
    category: "lighting",
    price: 119,
    rating: 4.6,
    reviewCount: 287,
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    description:
      "An LED desk lamp with stepless brightness and color-temperature adjustment from 2700 K to 6500 K. The auto-dimming sensor adapts to ambient light, and the slim aluminum arm folds flat when not in use.",
    specs: {
      "Color Temperature": "2700 K – 6500 K",
      Brightness: "Stepless dimming",
      "Max Output": "800 lumens",
      "LED Lifespan": "50,000 hrs",
      Material: "Aluminum + ABS",
      Power: "USB-C, 15 W",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-022",
    slug: "vexon-neon-strip",
    name: "Vexon Neon Strip",
    brand: "Vexon",
    category: "lighting",
    price: 39,
    rating: 4.3,
    reviewCount: 412,
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    ],
    description:
      "Flexible RGBIC LED strip with 16 million colors and music-sync mode that pulses to your playlist. The adhesive backing and cuttable design let you line desks, shelves, or monitors for immersive ambient lighting.",
    specs: {
      Length: "3 m",
      LEDs: "90 RGBIC",
      Colors: "16.7 million",
      Control: "App + voice (Alexa / Google)",
      Waterproof: "IP65",
      Power: "USB, 10 W",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-023",
    slug: "morn-torchiere-floor-lamp",
    name: "Morn Torchiere Floor Lamp",
    brand: "Morn",
    category: "lighting",
    price: 169,
    rating: 4.5,
    reviewCount: 94,
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    description:
      "A sculptural floor lamp with a brushed brass stem and an oversized linen shade that casts a warm, diffused glow. The foot-switch dimmer lets you dial in the perfect reading or mood light.",
    specs: {
      Height: "165 cm",
      Material: "Steel + linen shade",
      Bulb: "E27, 12 W LED included",
      Dimmer: "Foot-switch stepless",
      "Color Temperature": "3000 K",
      Weight: "7.2 kg",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-024",
    slug: "siltra-clip-light",
    name: "Siltra Clip Light",
    brand: "Siltra",
    category: "lighting",
    price: 22,
    rating: 4.2,
    reviewCount: 168,
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    description:
      "A portable clip-on reading light with a flexible gooseneck and three brightness levels. It clamps securely to books, headboards, or desks, and the rechargeable battery lasts up to 20 hours per charge.",
    specs: {
      Brightness: "3 levels",
      "Color Temperature": "4000 K",
      "Battery Life": "Up to 20 hrs",
      Charging: "Micro-USB, 2 hrs",
      "Clamp Width": "Up to 5 cm",
      Weight: "95 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-025",
    slug: "kovo-drift-hoodie",
    name: "Kovo Drift Hoodie",
    brand: "Kovo",
    category: "apparel",
    price: 69,
    rating: 4.5,
    reviewCount: 317,
    images: [
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
      "https://images.unsplash.com/photo-1490312278390-ab640c6a7fa9?w=800&q=80",
    ],
    description:
      "A midweight French-terry hoodie with a relaxed fit and a brushed fleece interior that feels soft from the first wear. The kangaroo pocket features a hidden media port, and the ribbed cuffs hold their shape wash after wash.",
    specs: {
      Material: "80% cotton / 20% polyester",
      Fit: "Relaxed",
      Weight: "380 gsm French terry",
      Pocket: "Kangaroo with media port",
      "Care": "Machine wash cold",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-026",
    slug: "nordhal-drift-sneakers",
    name: "Nordhal Drift Sneakers",
    brand: "Nordik",
    category: "apparel",
    price: 109,
    originalPrice: 139,
    discount: 22,
    rating: 4.6,
    reviewCount: 245,
    images: [
      "https://images.unsplash.com/photo-1490312278390-ab640c6a7fa9?w=800&q=80",
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
    ],
    description:
      "Low-top sneakers crafted from full-grain leather with a cushioned EVA midsole and a natural rubber cupsole. The OrthoLite insole and padded collar provide all-day comfort whether you are walking or commuting.",
    specs: {
      Upper: "Full-grain leather",
      Midsole: "EVA foam",
      Outsole: "Natural rubber cupsole",
      Insole: "OrthoLite",
      Closure: "Waxed cotton laces",
      Weight: "360 g per shoe",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-027",
    slug: "gravis-shadow-jacket",
    name: "Gravis Shadow Jacket",
    brand: "Gravit",
    category: "apparel",
    price: 189,
    rating: 4.4,
    reviewCount: 103,
    images: [
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
    ],
    description:
      "A lightweight softshell jacket with a DWR finish and a breathable membrane that blocks wind while releasing excess heat. Zippered hand pockets and an adjustable hood make it ready for unpredictable weather.",
    specs: {
      Material: "3-layer softshell, DWR finish",
      Windproof: "Yes",
      Breathability: "10,000 g/m²/24h",
      Hood: "Adjustable, stowable",
      Pockets: "2 hand + 1 chest zip",
      Weight: "480 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-028",
    slug: "morn-merino-tee",
    name: "Morn Merino Tee",
    brand: "Morn",
    category: "apparel",
    price: 59,
    rating: 4.3,
    reviewCount: 78,
    images: [
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
      "https://images.unsplash.com/photo-1490312278390-ab640c6a7fa9?w=800&q=80",
    ],
    badge: "New",
    description:
      "An ultra-soft merino wool t-shirt that naturally regulates temperature, resists odors, and wicks moisture. The flatlock seams eliminate chafing, making it a go-to base layer for travel and active days alike.",
    specs: {
      Material: "100% merino wool, 18.5 micron",
      Weight: "150 gsm",
      Odor: "Naturally resistant",
      "UPF Rating": "UPF 30+",
      Seams: "Flatlock stitching",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-029",
    slug: "lumio-mist-diffuser",
    name: "Lumio Mist Diffuser",
    brand: "Lumio",
    category: "home",
    price: 49,
    rating: 4.5,
    reviewCount: 204,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80",
    ],
    description:
      "An ultrasonic aroma diffuser with a 300 ml reservoir and seven LED mood-light colors. Its whisper-quiet operation and auto-shutoff safety feature make it ideal for bedrooms, offices, and yoga studios.",
    specs: {
      Capacity: "300 ml",
      Runtime: "Up to 10 hrs",
      Mist: "Ultrasonic, adjustable output",
      Lighting: "7-color LED",
      "Auto Shutoff": "Yes, low-water sensor",
      Coverage: "Up to 30 m²",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-030",
    slug: "veonar-thermo-stat",
    name: "Veonar Thermo Stat",
    brand: "Veonar",
    category: "home",
    price: 139,
    rating: 4.4,
    reviewCount: 185,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1598327105666-1a5dceb0a0c1?w=800&q=80",
    ],
    description:
      "A smart thermostat that learns your routine and builds an energy-saving schedule automatically. The crisp e-ink display blends into any wall, and remote control is available through the companion app.",
    specs: {
      Compatibility: "95% of HVAC systems",
      Connectivity: "Wi-Fi, Bluetooth LE",
      Display: "E-ink touchscreen",
      Sensors: "Temp, humidity, proximity",
      "Energy Reports": "Monthly via app",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-031",
    slug: "morn-studio-planter",
    name: "Morn Studio Planter",
    brand: "Morn",
    category: "home",
    price: 34,
    rating: 4.4,
    reviewCount: 67,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    description:
      "A set of three matte-glazed ceramic planters in graduated sizes, each with a built-in drainage tray. Their minimalist cylindrical silhouette complements modern, Scandinavian, and industrial interiors alike.",
    specs: {
      Material: "Matte-glazed stoneware",
      Sizes: "12 / 18 / 24 cm diameter",
      Drainage: "Integrated tray",
      Finish: "Matte white + speckled clay",
      Indoor: "Yes",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-032",
    slug: "siltra-linen-throw",
    name: "Siltra Linen Throw",
    brand: "Siltra",
    category: "home",
    price: 65,
    rating: 4.6,
    reviewCount: 143,
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
    ],
    description:
      "A stonewashed linen throw blanket that arrives soft and only gets better with every wash. Drape it over a sofa, layer it at the foot of the bed, or take it outside for cool evenings on the patio.",
    specs: {
      Material: "100% French flax linen",
      Dimensions: "150 × 200 cm",
      "GSM Weight": "180 gsm",
      Certifications: "OEKO-TEX Standard 100",
      "Care": "Machine wash gentle, tumble dry low",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-033",
    slug: "vexon-rift-mouse",
    name: "Vexon Rift Mouse",
    brand: "Vexon",
    category: "gaming",
    price: 59,
    originalPrice: 89,
    discount: 34,
    rating: 4.7,
    reviewCount: 528,
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "An ultralight 59 g wireless gaming mouse with a 26K DPI optical sensor and optical switches rated for 90 million clicks. Its hex-cut shell and paracord charging cable make it a top choice for competitive play.",
    specs: {
      Sensor: "Optical, 26K DPI",
      Weight: "59 g",
      Switches: "Optical, 90M lifespan",
      Connectivity: "2.4 GHz wireless + USB-C",
      "Battery Life": "Up to 70 hrs",
      "Polling Rate": "1000 Hz",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-034",
    slug: "kovo-void-headset",
    name: "Kovo Void Headset",
    brand: "Kovo",
    category: "gaming",
    price: 89,
    rating: 4.5,
    reviewCount: 398,
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    ],
    description:
      "Over-ear gaming headset with 50 mm neodymium drivers, a retractable boom mic, and memory-foam ear cushions. Virtual 7.1 surround sound gives you a competitive edge, and the lightweight frame stays comfortable for marathon sessions.",
    specs: {
      Drivers: "50 mm neodymium",
      Surround: "Virtual 7.1",
      Mic: "Retractable unidirectional",
      Connectivity: "USB + 3.5 mm",
      "Cable Length": "2 m braided",
      Weight: "280 g",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-035",
    slug: "pallax-apex-controller",
    name: "Pallax Apex Controller",
    brand: "Pallax",
    category: "gaming",
    price: 74,
    rating: 4.5,
    reviewCount: 263,
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80",
    ],
    description:
      "A pro-grade wireless controller with four remappable back paddles and Hall-effect thumbsticks that eliminate drift. Adjustable trigger stops and swappable thumbstick caps let you dial in your ideal setup.",
    specs: {
      Connectivity: "2.4 GHz + Bluetooth 5.0",
      Sticks: "Hall-effect anti-drift",
      Paddles: "4 remappable back buttons",
      "Trigger Stops": "3-position switches",
      "Battery Life": "Up to 25 hrs",
      "Platform Support": "PC, console, mobile",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-036",
    slug: "gravis-arena-desk",
    name: "Gravis Arena Desk",
    brand: "Gravit",
    category: "gaming",
    price: 349,
    rating: 4.5,
    reviewCount: 156,
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    ],
    description:
      "A wide 160 cm gaming desk with a carbon-fiber-textured surface, a full-desk mouse pad, and dual motorized height adjustment. Built-in cable management and a headphone hook keep your setup clean and battle-ready.",
    specs: {
      Width: "160 cm",
      Depth: "75 cm",
      Height: "72 – 118 cm (motorized)",
      Material: "Steel frame + MDF top",
      "Surface Coating": "Carbon-fiber texture",
      "Max Load": "100 kg",
    },
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: "prod-037",
    slug: "nordhal-trail-pack",
    name: "Nordhal Trail Pack",
    brand: "Nordik",
    category: "outdoor",
    price: 129,
    rating: 4.6,
    reviewCount: 211,
    images: [
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
      "https://images.unsplash.com/photo-1490312278390-ab640c6a7fa9?w=800&q=80",
    ],
    description:
      "A 40-liter hiking backpack with an adjustable AirFlow suspension system and a rain cover stored in its own pocket. Multiple lash points, trekking-pole loops, and a hydration sleeve keep you trail-ready for multi-day treks.",
    specs: {
      Capacity: "40 L",
      Material: "210D ripstop nylon",
      Frame: "Adjustable AirFlow suspension",
      "Hydration Sleeve": 'Up to 3 L reservoir',
      "Rain Cover": "Included, stowable",
      Weight: "1.3 kg",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: "prod-038",
    slug: "kovo-summit-bottle",
    name: "Kovo Summit Bottle",
    brand: "Kovo",
    category: "outdoor",
    price: 27,
    rating: 4.5,
    reviewCount: 334,
    images: [
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    ],
    description:
      "A 750 ml double-wall vacuum-insulated bottle that keeps drinks cold for 24 hours or hot for 12. The leak-proof twist cap and powder-coated exterior withstand drops, scratches, and daily adventures.",
    specs: {
      Capacity: "750 ml",
      Material: "18/8 stainless steel",
      Insulation: "Double-wall vacuum",
      "Cold Retention": "24 hrs",
      "Hot Retention": "12 hrs",
      Weight: "340 g",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-039",
    slug: "gravis-trail-chair",
    name: "Gravis Trail Chair",
    brand: "Gravit",
    category: "outdoor",
    price: 45,
    originalPrice: 69,
    discount: 35,
    rating: 4.3,
    reviewCount: 178,
    images: [
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80",
    ],
    badge: "Sale",
    description:
      "A collapsible camping chair with a sturdy aluminum frame and a breathable mesh backrest. It folds down to the size of a water bottle and includes a built-in cup holder and side pocket for snacks or a phone.",
    specs: {
      Material: "600D polyester + aluminum",
      "Weight Capacity": "120 kg",
      "Folded Size": "35 × 12 × 12 cm",
      Weight: "1.1 kg",
      Features: "Cup holder + side pocket",
    },
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: "prod-040",
    slug: "siltra-outrider-multitool",
    name: "Siltra Outrider Multitool",
    brand: "Siltra",
    category: "outdoor",
    price: 49,
    rating: 4.7,
    reviewCount: 189,
    images: [
      "https://images.unsplash.com/photo-1501554726770-470e11ab0b16?w=800&q=80",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    ],
    badge: "Limited",
    description:
      "A 16-in-1 multitool forged from stainless steel with a locking blade, pliers, bit driver, and a fire starter. The compact nylon sheath slides onto any belt, and each tool locks securely for safe, confident use.",
    specs: {
      Tools: "16 functions",
      Material: "420HC stainless steel",
      "Blade Length": "6.5 cm",
      "Locking": "Liner lock on all tools",
      Weight: "240 g",
      Sheath: "Ballistic nylon",
    },
    inStock: true,
    featured: true,
    trending: false,
  },
]
