import type { Review } from "@/types"

export const testimonials: Review[] = [
  {
    id: "test-001",
    productId: "prod-001",
    author: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
    title: "Absolutely love this purchase",
    body: "The quality exceeded my expectations. The design is sleek and it works perfectly with my setup. Couldn't be happier with the purchase.",
    date: "2026-01-15",
  },
  {
    id: "test-002",
    productId: "prod-005",
    author: "Marcus Johnson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 5,
    title: "Premium feel, worth every penny",
    body: "I've tried many similar products but this one stands out. The build quality is exceptional and the attention to detail is remarkable.",
    date: "2026-02-03",
  },
  {
    id: "test-003",
    productId: "prod-010",
    author: "Emily Rodriguez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 4,
    title: "Great product, fast shipping",
    body: "Really impressed with how quickly it arrived. The product itself is fantastic — exactly as described. Would definitely buy again.",
    date: "2026-02-18",
  },
  {
    id: "test-004",
    productId: "prod-015",
    author: "James Wilson",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    rating: 5,
    title: "Best in class",
    body: "After comparing multiple options, this was clearly the best choice. The performance is outstanding and the design is minimal yet functional.",
    date: "2026-03-01",
  },
  {
    id: "test-005",
    productId: "prod-020",
    author: "Lisa Park",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80",
    rating: 5,
    title: "A game changer for my workflow",
    body: "This has completely transformed how I work. The ergonomics are perfect and the functionality is exactly what I needed.",
    date: "2026-03-12",
  },
  {
    id: "test-006",
    productId: "prod-025",
    author: "David Kim",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    rating: 4,
    title: "Solid quality at a fair price",
    body: "The value proposition here is incredible. You get premium quality without the premium price tag. Highly recommended.",
    date: "2026-03-25",
  },
  {
    id: "test-007",
    productId: "prod-008",
    author: "Anna Thompson",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    rating: 5,
    title: "Perfect gift idea",
    body: "Bought this as a gift and the recipient was thrilled. The packaging alone feels premium. Will be ordering more for myself.",
    date: "2026-04-08",
  },
  {
    id: "test-008",
    productId: "prod-012",
    author: "Michael Torres",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80",
    rating: 4,
    title: "Great everyday carry",
    body: "I use this daily and it holds up beautifully. The material quality is top-notch and it still looks brand new after months of use.",
    date: "2026-04-20",
  },
]
